name: Java ATMManagement Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-atm-management:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Compile Java code
        run: |
          mkdir -p bin
          javac -d bin src/ATMManagement.java

      - name: Run ATMManagement with multiple inputs
        run: |
          # Replace the input string below with your actual inputs
          echo -e "1234" | java -cp bin ATMManagement
