name: Java CI without build tools

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Compile Java files
      run: |
        mkdir -p bin
        javac -d bin src/*.java

    - name: Run ATMManagement Class
      run: |
        java -cp bin ATMManagement
